"""create_scope_definitions_table

Revision ID: 5b205d373568
Revises: ae1acf3f1c6e
Create Date: 2026-03-01 12:10:52.362256
"""
from typing import Sequence, Union

import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b205d373568'
down_revision: Union[str, None] = 'ae1acf3f1c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('claims', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('required_roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_definitions_name'), 'scope_definitions', ['name'], unique=True)

    # Seed default scopes
    scope_definitions = sa.table(
        'scope_definitions',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
        sa.column('claims', postgresql.JSON()),
        sa.column('required_roles', postgresql.JSON()),
        sa.column('icon', sa.String()),
        sa.column('sort_order', sa.Integer()),
        sa.column('is_active', sa.Boolean()),
        sa.column('is_system', sa.Boolean()),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(scope_definitions, [
        {
            'id': str(uuid.uuid4()), 'name': 'openid',
            'description': 'OpenID Connect identity',
            'claims': ['sub'], 'required_roles': [],
            'icon': 'Fingerprint', 'sort_order': 0,
            'is_active': True, 'is_system': True,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'profile',
            'description': 'User profile information',
            'claims': ['name', 'picture', 'bio'], 'required_roles': [],
            'icon': 'User', 'sort_order': 1,
            'is_active': True, 'is_system': False,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'email',
            'description': 'Email address',
            'claims': ['email', 'email_verified'], 'required_roles': [],
            'icon': 'Mail', 'sort_order': 2,
            'is_active': True, 'is_system': False,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'cohort',
            'description': 'NS cohort information',
            'claims': ['cohort'], 'required_roles': [],
            'icon': 'GraduationCap', 'sort_order': 3,
            'is_active': True, 'is_system': False,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'activity',
            'description': 'User activity and stats',
            'claims': ['posts_count', 'streak_days', 'last_active'], 'required_roles': [],
            'icon': 'Activity', 'sort_order': 4,
            'is_active': True, 'is_system': False,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'socials',
            'description': 'Social media links',
            'claims': ['socials'], 'required_roles': [],
            'icon': 'Share2', 'sort_order': 5,
            'is_active': True, 'is_system': False,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'wallet',
            'description': 'Blockchain wallet address',
            'claims': ['wallet_address'], 'required_roles': [],
            'icon': 'Wallet', 'sort_order': 6,
            'is_active': True, 'is_system': False,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'roles',
            'description': 'Discord roles in the NS server',
            'claims': ['roles'], 'required_roles': [],
            'icon': 'Shield', 'sort_order': 7,
            'is_active': True, 'is_system': False,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'date_joined',
            'description': 'Account creation date',
            'claims': ['date_joined'], 'required_roles': [],
            'icon': 'Calendar', 'sort_order': 8,
            'is_active': True, 'is_system': False,
            'created_at': datetime.now(timezone.utc),
        },
        {
            'id': str(uuid.uuid4()), 'name': 'offline_access',
            'description': 'Long-lived refresh tokens',
            'claims': [], 'required_roles': [],
            'icon': 'RefreshCw', 'sort_order': 9,
            'is_active': True, 'is_system': True,
            'created_at': datetime.now(timezone.utc),
        },
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scope_definitions_name'), table_name='scope_definitions')
    op.drop_table('scope_definitions')
    # ### end Alembic commands ###
