"""add is_admin to users and status to oauth_apps

Revision ID: ae1acf3f1c6e
Revises: aeb032954e50
Create Date: 2026-02-24 21:46:34.015537
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1acf3f1c6e'
down_revision: Union[str, None] = 'aeb032954e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_apps', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('oauth_apps', 'status')
    # ### end Alembic commands ###
