"""replace privy_did with discord fields

Revision ID: aeb032954e50
Revises: f1c497610bd4
Create Date: 2026-02-18 22:39:24.371381
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeb032954e50'
down_revision: Union[str, None] = 'f1c497610bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discord_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('discord_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('discord_avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('discord_roles', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_users_privy_did', table_name='users')
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.drop_column('users', 'privy_did')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privy_did', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.create_index('ix_users_privy_did', 'users', ['privy_did'], unique=True)
    op.drop_column('users', 'discord_roles')
    op.drop_column('users', 'discord_avatar')
    op.drop_column('users', 'discord_username')
    op.drop_column('users', 'discord_id')
    # ### end Alembic commands ###
