"""create_claim_definitions_and_widen_scope_icon

Revision ID: e6ec3c33120a
Revises: 58986b91f192
Create Date: 2026-03-01 13:21:08.440745
"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ec3c33120a'
down_revision: Union[str, None] = '58986b91f192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Seed claim definitions matching CLAIM_RESOLVERS keys
SEED_CLAIMS = [
    ("sub", "Subject", "Unique user identifier", "model"),
    ("email", "Email Address", "User's verified email", "model"),
    ("email_verified", "Email Verified", "Whether the email is verified", "computed"),
    ("name", "Display Name", "User's display name", "model"),
    ("picture", "Profile Picture", "URL to user's avatar", "model"),
    ("bio", "Bio", "User's biography", "model"),
    ("cohort", "Cohort", "User's NS cohort", "model"),
    ("roles", "Discord Roles", "User's Discord server roles", "model"),
    ("date_joined", "Date Joined", "When the user first signed up", "model"),
    ("wallet_address", "Wallet Address", "User's crypto wallet address", "model"),
    ("socials", "Social Links", "User's social media links", "model"),
    ("posts_count", "Posts Count", "Number of posts by user", "metadata"),
    ("streak_days", "Streak Days", "Current activity streak in days", "metadata"),
    ("last_active", "Last Active", "When the user was last active", "metadata"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    claim_table = op.create_table('claim_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_definitions_name'), 'claim_definitions', ['name'], unique=True)
    op.alter_column('scope_definitions', 'icon',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # Seed claim definitions
    now = datetime.now(timezone.utc)
    op.bulk_insert(claim_table, [
        {
            "id": str(uuid.uuid4()),
            "name": name,
            "label": label,
            "description": desc,
            "source": source,
            "is_active": True,
            "created_at": now,
        }
        for name, label, desc, source in SEED_CLAIMS
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scope_definitions', 'icon',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_claim_definitions_name'), table_name='claim_definitions')
    op.drop_table('claim_definitions')
    # ### end Alembic commands ###
