"""add icon_url and privacy_policy_url to oauth_apps

Revision ID: f857d09ae515
Revises: ed8b9d0ee5f2
Create Date: 2026-02-07 11:30:38.201233
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f857d09ae515'
down_revision: Union[str, None] = 'ed8b9d0ee5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_apps', sa.Column('icon_url', sa.Text(), nullable=True))
    op.add_column('oauth_apps', sa.Column('privacy_policy_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_apps', 'privacy_policy_url')
    op.drop_column('oauth_apps', 'icon_url')
    # ### end Alembic commands ###
